apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
