apiVersion: v1
kind: Pod
metadata:
  name: products-api
  labels:
    component: products-api
spec:
  containers:
  - name: products-api
    image: laithharb/products-api
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5002
